# ==========================================
# 1. Framework & Environment Settings
# ==========================================
env=qa
appium.url=http://127.0.0.1:4723/
implicit.wait=10
explicit.wait=20

# ==========================================
# 2. Local Device Settings (Android/iOS)
# ==========================================
android.device.name=Realme P1 5G
android.platform.version=16.0
android.app.path=E:\\Downloads\\app-prod-release.apk

ios.device.name=iPhone_14_Pro
ios.platform.version=16.0
ios.app.path=src/test/resources/apps/ios_app.ipa

# ==========================================
# 3. Cloud Provider Settings (BrowserStack)
# ==========================================
bs.user=your_username
bs.key=your_access_key
bs.app.url=bs://app_url_id
bs.project=Mobile_Automation_Framework

# ==========================================
# 4. Log4j 2 Configuration (Unified)
# ==========================================
# Root logger level (ERROR, WARN, INFO, DEBUG)
status = error
dest = err
name = PropertiesConfig

# Console Appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

# File Appender
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = logs/automation.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Logger Root
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = LOGFILE