# ==========================================
# 1. Framework & Environment Settings
# ==========================================
env=qa
appium.url=http://127.0.0.1:4723/
implicit.wait=10
explicit.wait=20

# ==========================================
# 2. Local Device Settings (Android/iOS)
# ==========================================
android.device.name=Realme P1 5G
android.platform.version=16.0
android.app.path=E:\\Downloads\\app-prod-release.apk
android.app.main.activity=com.chargepass.presto.MainActivity



ios.device.name=iPhone_14_Pro
ios.platform.version=16.0
ios.app.path=src/test/resources/apps/ios_app.ipa

# ==========================================
# 3. Cloud Provider Settings (BrowserStack)
# ==========================================
bs.user=your_username
bs.key=your_access_key
bs.app.url=bs://app_url_id
bs.project=Mobile_Automation_Framework

# ==========================================
# 4. Log4j 2 Configuration (Unified)
# ==========================================
# Root logger level (ERROR, WARN, INFO, DEBUG)
